defaults:
  - datasets: QH9-dynamic
ex_name: 'ex_name'
device: 2
ckpt_dir: 'checkpoints'
split_seed: 42
optimizer: adam
ema_start_epoch: -1

trained_model: '.'
# For evaluating trained model
seed: 0